[package]
name = "http_server"
version = "0.1.0"
edition = "2021"
authors = ["Ihor Kyrylchuk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
